name: boxcodes
description: "A Flutter app for keeping track of what is in a storage box and where the storage box is located at home!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2
  lints: ^3.0.0

flutter:
  uses-material-design: true
