// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTfP0V_9EvCoWN5f2wdWHLibDNI2j7C98',
    appId: '1:183693759680:web:d4eed181efeb65faf58925',
    messagingSenderId: '183693759680',
    projectId: 'boxn-bc8fa',
    authDomain: 'boxn-bc8fa.firebaseapp.com',
    storageBucket: 'boxn-bc8fa.appspot.com',
    measurementId: 'G-4N1XFTTTCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeZqisD7M2mYZnFVZz604kKAZ4ct-7yiQ',
    appId: '1:183693759680:android:fb8d8ec78c048343f58925',
    messagingSenderId: '183693759680',
    projectId: 'boxn-bc8fa',
    storageBucket: 'boxn-bc8fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4GHvKTNHk0CiL-_HvBl-GM1ZioNzMmWo',
    appId: '1:183693759680:ios:22396060f89f92a0f58925',
    messagingSenderId: '183693759680',
    projectId: 'boxn-bc8fa',
    storageBucket: 'boxn-bc8fa.appspot.com',
    iosBundleId: 'com.example.boxcodes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4GHvKTNHk0CiL-_HvBl-GM1ZioNzMmWo',
    appId: '1:183693759680:ios:22396060f89f92a0f58925',
    messagingSenderId: '183693759680',
    projectId: 'boxn-bc8fa',
    storageBucket: 'boxn-bc8fa.appspot.com',
    iosBundleId: 'com.example.boxcodes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTfP0V_9EvCoWN5f2wdWHLibDNI2j7C98',
    appId: '1:183693759680:web:e02e796a1abd9a6ff58925',
    messagingSenderId: '183693759680',
    projectId: 'boxn-bc8fa',
    authDomain: 'boxn-bc8fa.firebaseapp.com',
    storageBucket: 'boxn-bc8fa.appspot.com',
    measurementId: 'G-9Z2MLRDH9X',
  );
}
